export { HomePage } from './HomePage'
export { ProjectsPage } from './ProjectsPage'
export { EditorPage } from './EditorPage'
export { ProfilePage } from './ProfilePage'
export { AboutPage } from './AboutPage'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
